source_image_dir = "image_dataset"

target_res = [1024, 896]

caption_shuffle_variants = 4

caption_tag_dropout_rate = 0.1

caption_tag_randomize_rate = 0.0

caption_position_clauses = false

sigma_demote = "1024:896,1024:768"

drop_lowres_images = true
min_pixels = 250000

freefit_max_ratio = 4.0
